//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMassage
    {
        public long IdMessage { get; set; }
        public long SenderID { get; set; }
        public long TopicID { get; set; }
        public System.DateTime Time { get; set; }
        public string Massage { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual employees employees { get; set; }
    }
}
