//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeChatRoom
    {
        public long ID { get; set; }
        public long EmployeeID { get; set; }
        public long ChatRoomID { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual employees employees { get; set; }
    }
}
